language: java
install: true

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      tags: true
      branch: master